# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b5d257e814ea81354b10e8044ea3868db329b14216c4b773e4a4aa3855c657e043162d31dbe01e2a92c4e6837f3e4b89859f2ef2e15dfdcab753f55a930fc49a

test:
  secret_key_base: a34c71f3661cbb63e12f09c9670ee452085713a2bed751fd0790aa6aebce03719306d4402dc47ff793b38256785911d5f974c45a1e7e69d3c248eeafdb2fa12e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
